### PR TITLE
Add basic implementation of logic

### PR DESCRIPTION
**Pull request by gtvj**
**DO NOT MERGE UNTIL**

- [ ] @ma2ts is happy that everything is working OK
- [x] the function to handle legacy sub-class series has been written and tested (against a number of references - to be provided by Matt)

Hi @ma2ts, 

This is the first part of the feature which aims to ensure we're getting the right guides for a specific reference. Could you take a look at this and tell me if it's working? You should be able to run the code by following these steps.

1. Clone the repository,  check out this branch and `cd` into the project root.
2. Change the variable `test_reference` in `app.js` to be a reference you'd like to test.
3. run `node app.js` and see the results as printed to the console. It should look something like this
4. Repeat steps 3. and 4. for other references

### CODE REVIEW

**Comment by ma2ts** [comment]
Hi @gtvj 
I've been testing the code today and working out real test references for the 13 possible combinations of record hierarchy and/or guide availability.

As of this PR it looks like 4 of the 13 test cases behave well, 4 partially fail and 5 completely fail.  I've added a file to the repo that details the 13 test references, their current test status, and what guides (if any) I would expect to see from each reference.

I've also added an extra paragraph to section 2. of my original methodology file that explains the 20 rare non-standard series level references that occur from time to time (and which you will also have to take into account during the reference splitting as they do have guide links unfortunately!) :-(

Cheers,
Matt

**Comment by gtvj** [comment]
Hi @ma2ts, 

I think I've fixed this now, and I've added tests to cover the 13 possible combinations of record hierarchy and/or guide availability you've identified. These tests can be run by running `npm install` followed by `mocha` from the project root. I've tried to write the tests in such a way that we can add additional cases without needing to write additional tests. All the tests are in the `test` directory and it should be quite simple to add to them.

You can also still run the code against a specific reference by updating the `test_reference` variable in `app.js` and then running `node app.js`. 

I've also tried to improve the logging output and have stubbed out a function to extract the variables from legacy sub-class series (though there is no code in there at present).

**Comment by ma2ts** [comment]
Hi @gtvj 
Looking good! 12 out of the 13 tests now pass as far as I'm concerned - and the single 'failure' fails gracefully. This is the very first test where the reference is nothing but a lettercode. So, using the example of 'AB', the return is as follows:

iven AB reference, these fragments were extracted:
+-----------------------------------------------------------+
¦ Extracted letter code ¦ Extracted series ¦ Full reference ¦
¦-----------------------+------------------+----------------¦
¦ false                 ¦ false            ¦ AB             ¦
+-----------------------------------------------------------+

For these fragments, the identified guides were:
+-----------------------------------+
¦       ¦ Number of guides ¦ Guides ¦
¦-------+------------------+--------¦
¦ false ¦ 0                ¦        ¦
¦-------+------------------+--------¦
¦ false ¦ 0                ¦        ¦
¦-------+------------------+--------¦
¦ AB    ¦ 0                ¦        ¦
+-----------------------------------+

However, I would expect the code to detect that there is a guide available for lettercode 'AB', i.e. "Contaminated land"

Also (tiny point) but there is also a missing "G" at the start of the results: "iven ..." instead of "Given ..."

**Comment by gtvj** [comment]
Hi @ma2ts - thanks for spotting this. It was a problem with the RegEx that extracts the letter code (it was expecting a space). I've updated the RegEx and introduced an associated test in the latest commit. All should be working OK now. Could you take a look? 

I'm not having the missing 'G' problem. Could I take a look on your machine? 

Also, could you give me perhaps half a dozen of the legacy sub-class references that I could write some tests around.

**Comment by ma2ts** [comment]
Hi @gtvj 
Sorry but the sub-class references don't seem to be working yet...
Here are some examples, and the guides I would expect to see:

**CP 25/2**
----[non from lettercode CP]
--------"Land and property ownership: conveyances by feet of fines 1182-1833"
--------"Land and property ownership: enrolment and registration of title 1227-c1930"

**CP 25/1/284/18**
----[non from lettercode CP]
--------"General eyres 1194-1348"
--------"Land and property ownership: enrolment and registration of title 1227-c1930"
----------------"Court of King's Bench records 1200-1702"

**IR 121/1**
----"Taxation" [from lettercode IR]
--------"Land use, value and ownership: Valuation Office Survey 1910-1915"
--------"Maps: further research"
--------"Ordnance Survey"

**PRO 31/8/140B**
----[non from lettercode PRO]
--------"Foreign affairs before 1509"
--------"State Papers Ireland 1509-1782"
----------------"Religious houses and their lands c.1000-1530"

**Comment by gtvj** [comment]
Hi @ma2ts - I hadn't written the code to handle legacy sub series but have now. I've also introduced tests covering all the references you've listed below (which can be run with the `mocha` command from the project root). Hopefully everything should be working as expected now. Could you have a look and let me know? Cheers, G

**Pull request merged**
